apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: android-generator-notls
  namespace: web
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: android-generator
          servicePort: 8080
